version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8090:8080"

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=cortex
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: DOCKERFILE
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - mariadb

  frontend:
    build:
      context: ./frontend
      dockerfile: DOCKERFILE
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  esdata:
  mariadbdata: